export const projects = [
  {
    title: 'Titans Arena (Team Project)',
    description: "A gaming platform featuring official game information, pre-registration, tournament management, and a gaming blog. Built using React, Tailwind CSS, and Redux RTK Query for the frontend and Firebase with MongoDB and Express for secure, scalable backend functionality.",
    image: '../../out/images/titans-arena.web.app_.png',
    tags: ['React,', 'Redux,', 'RTK Query,', 'Tailwind CSS,', 'Firebase,', 'MongoDB,', 'Express.'],
    source: 'https://github.com/your-repo/titans-arena-frontend',
    visit: 'https://titansarena.com',
    id: 1,
  },
  {
    title: 'Task Manager - Organize Your Tasks',
    description: "A task management tool designed to simplify task organization and improve productivity. Built using React, React-Redux, and Tailwind CSS with a backend powered by Firebase, MongoDB, and Express.",
    image: '/images/task_manager.jpg',
    tags: ['React,', 'Redux,', 'Tailwind CSS,', 'Firebase,', 'MongoDB,', 'Express,'],
    source: 'https://github.com/your-repo/task-manager-frontend',
    visit: 'https://taskmanager.com',
    id: 2,
  },
  {
    title: 'LearnIQ - Learning-Based Toy Website',
    description: "A single-page website offering categorized educational toys for children. Developed with React, React Router, and Tailwind CSS for a seamless user experience, with secure authentication via Firebase and a backend powered by MongoDB and Express.",
    image: '/images/learniq.jpg',
    tags: ['React', 'React Router', 'Tailwind CSS', 'Firebase', 'MongoDB', 'Express'],
    source: 'https://github.com/your-repo/learniq-frontend',
    visit: 'https://learniq.com',
    id: 3,
  },
  {
    title: 'Mogo',
    description: "A static website built to showcase design and functionality using HTML, CSS, and JavaScript.",
    image: '/images/mogo.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/saiful-islam-dev/mogo',
    visit: 'https://saiful-islam-dev.github.io/mogo/',
    id: 4,
  },
  {
    title: 'Kub',
    description: "A static website focused on responsive design and interactivity, built using HTML, CSS, and JavaScript.",
    image: '/images/kub.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/saiful-islam-dev/kub',
    visit: 'https://saiful-islam-dev.github.io/kub/',
    id: 5,
  },
  {
    title: 'Cameroon',
    description: "A visually appealing static website designed with a focus on creative layout and UI enhancements.",
    image: '/images/cameroon.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/saiful-islam-dev/Cameroon',
    visit: 'https://saiful-islam-dev.github.io/Cameroon/',
    id: 6,
  },
  {
    title: 'Waxom',
    description: "A responsive and aesthetically pleasing static website created with HTML, CSS, and JavaScript.",
    image: '/images/waxom.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/saiful-islam-dev/Waxom',
    visit: 'https://saiful-islam-dev.github.io/Waxom/',
    id: 7,
  },
  {
    title: 'Manage',
    description: "A modern website showcasing a clean design and optimized for responsiveness and performance.",
    image: '/images/manage.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/saiful-islam-dev/manage',
    visit: 'https://saiful-islam-dev.github.io/manage/',
    id: 8,
  },
];


export const TimeLineData = [
  { year: 2016, text: 'Started my Diploma in Computer Engineering, sparking a keen interest in technology.' },
  { year: 2020, text: 'Focused on my studies. When the COVID-19 pandemic hit, I adapted to the challenges and acquired new skills.' }, // clarified and improved sentence structure
  { year: 2022, text: 'Started learning PHP and Laravel. Completed a dedicated course and finished my Diploma in Computer Engineering.' },
  { year: 2023, text: 'Learned the MERN Stack and took a course from Programming Hero. Competed in a team competition, finishing in the top 5.' },
  { year: 2024, text: 'Advanced my skills with new technologies and enrolled in another course from Programming Hero.' },
];